<!DOCTYPE html>
<html>

<head>
  <title>Geekritic</title>






  <?php

  include('includes/header.php');


  ?>


</head>

<body>




  <?php
  include('includes/nav.php');
  ?>




  <div class="desc">
    <div class="row">
      <div class="desc-2 col-md-4">
        <img src="assets/images/2442891.jpg" class="filme">
      </div>

      </dv>
      <div class="row">
        <div class="desc-2 col-md-8">
          <div class="desc-item">
            <div class="desc-item">
              <h2 class="">O Exterminador do Futuro: Destino Sombrio</h2>
              <span class="light">Lançamento: </span>
              <a>31 de outubro de 2019</a>
            </div>

            <div class="">
              <span class="light">Direção: </span>
              <a>Tim Miller</a>
            </div>

            <div class="">
              <span class="light">Gêneros: </span>
              <a><a href="acao.php">Ação</a>, Ficção científica</a>
            </div>

            <div class="">
              <span class="light">Nacionalidade: </span>
              <a>EUA</a>
            </div>

            <div style="text-align: center;">
              <a> Na sexta aventura da saga Exterminador do Futuro, Arnold Schwarzenegger interpreta novamente o papel icônico de T-800, enquanto Linda Hamilton encarna mais uma vez Sarah Connor.</a>
            </div>
          </div>
        </div>

      </div>
    </div>
































    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Login</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form class="px-4 py-3">
              <div class="form-group">
                <label for="exampleDropdownFormEmail1">Endereço de e-mail</label>
                <input type="email" class="form-control" id="exampleDropdownFormEmail1" placeholder="email@example.com">
              </div>
              <div class="form-group">
                <label for="exampleDropdownFormPassword1">Senha</label>
                <input type="password" class="form-control" id="exampleDropdownFormPassword1" placeholder="Password">
              </div>
              <div class="form-group">
                <div class="form-check">
                  <input type="checkbox" class="form-check-input" id="dropdownCheck">
                  <label class="form-check-label" for="dropdownCheck">
                    Lembrar Senha
                  </label>

                </div>
              </div>
              <a class="dropdown-item" style="margin-left:-20px" href="/cadastro.php">Cadastre-se</a>
            </form>
            <div>

            </div>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            <button type="button" class="btn btn-primary">Entrar</button>
          </div>

        </div>

      </div>
    </div>
  </div>









  <?php

  include('includes/rodape.php');


  ?>


</body>

</html>